In [10]:
import pandas as pd
import re

In [15]:
# Read CSV file
csv_file = "C:/Users/konye/Downloads/dataUpload.csv"
df = pd.read_csv(csv_file)

# # Remove '?' from column names
# df.columns = df.columns.str.replace('?', '')

# Remove text within brackets (including the brackets) and question marks from column names
df.columns = df.columns.str.replace(r'\s*[\(\[].*?[\)\]]|\?', '', regex=True)

# Remove anything after a slash (including the slash) from column names
df.columns = df.columns.str.split('/').str[0]

In [16]:
def clean_dataframe(df):
    # Trim column names, convert to lowercase, and replace spaces with underscores
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
    
    # Trim all string values in the DataFrame
    df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
    
    return df
clean_df = clean_dataframe(df)
df = clean_df.drop('s', axis=1)
df

,state,lga,facility,patient_id,hospital_number,unique_id,household_unique_no,received_ovc_service,sex,current_weight,...,cervical_cancer_screening_type,cervical_cancer_screening_method,result_of_cervical_cancer_screening,date_of_precancerous_lesions_treatment,precancerous_lesions_treatment_methods,date_biometrics_enrolled,valid_biometrics_enrolled,iit_chance,date_calculated,case_manager
0,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",002cecc5-72c5-4613-84a6-3e283e36f83d,oss/kn/22/2/3353,oss/kn/22/2/3353,NaN,NaN,Male,71.0,...,NaN,NaN,NaN,NaN,NaN,07/11/2022,Yes,NaN,NaN,NaN
1,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",00385a04-5e56-419b-8d75-ac8819f662eb,OSS/KN/22/6/4343,OSS/KN/22/6/4343,NaN,NaN,Male,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",0047b46d-4e6b-4df2-8414-82371c41343d,oss/kn/22/1/5059,oss/kn/22/1/5059,NaN,NaN,Female,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",005b3334-9d26-40ea-8f38-9bc9976670a1,OSS/KN/19/3/0467,OSS/KN/19/3/0467,NaN,NaN,Male,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",006d70da-7646-4ac3-b452-0e6e156684c1,OSS/KN/20/1/1463,OSS/KN/20/1/1463,NaN,NaN,Female,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2333,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",ff843463-b6e5-4071-afdd-dac8c17e3475,OSS/KN/23/2/8624,OSS/KN/23/2/8624,NaN,NaN,Male,49.0,...,NaN,NaN,NaN,NaN,NaN,44949,Yes,NaN,NaN,NaN
2334,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",ff997234-a5a8-4f73-a0bd-4263bb2a6bf0,OSS/KN/22/3/6521,OSS/KN/22/3/6521,NaN,NaN,Female,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2335,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",ffa1d041-f4ba-4ff6-8b4c-40a78762b776,OSS/KN/19/2/0964,OSS/KN/19/2/0964,NaN,NaN,Female,48.0,...,NaN,NaN,NaN,NaN,NaN,44831,Yes,NaN,NaN,NaN
2336,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",ffbefe4c-e5db-449b-b913-823a9906c323,oss/kn/22/1/3828,oss/kn/22/1/3828,NaN,NaN,Female,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2337,Kano,Nasarawa,"Kano State One Stop Shop (OSS), Nasarawa",ffe4261a-1feb-4f5a-b7b0-3c494498c8f1,oss/kn/22/2/4169,oss/kn/22/2/4169,NaN,NaN,Male,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# Convert DataFrame to XML
# df1 = df.copy()
# df1 = df1.drop('S/No.', axis=1)
xml_output_file = 'C:/Users/konye/Downloads/dataUpload.xml'
df.to_xml(xml_output_file, index=False, root_name='Root', row_name='Row')

In [18]:
# Convert DataFrame to JSON
json_output_file = 'C:/Users/konye/Downloads/dataUpload.json'
df.to_json(json_output_file, orient='records', date_format='iso')

In [16]:
from app import app
from models import FacilityNameItem, ClientIdItem, DataEntry, Facility

In [5]:
with app.app_context():
    facilities = FacilityNameItem.query.all()

    for facility in facilities:
        print(f"ID: {facility.id}, Facility Name: {facility.facility_name}")

ID: 1, Facility Name: Kano State One Stop Shop (OSS), Nasarawa
ID: 2, Facility Name: Abuja Hospital

In [22]:
with app.app_context():
    facitems = Facility.query.all()

    for f in facitems:
        print(f"ID: {f.id}, Facility Name: {f.facility_name}, State: {f.state}, LGA: {f.lga}")

ID: 1, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, State: Kano, LGA: Nasarawa
ID: 2, Facility Name: Abuja Hospital, State: FCT, LGA: AMAC

In [21]:
with app.app_context():
    items = DataEntry.query.all()

    for f in items:
        print(f"Client ID: {f.client_id}, Facility Name: {f.facility_name}, Current(ndr)?: {f.curr_ll}")

Client ID: oss/kn/22/2/3353, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: yes
Client ID: OSS/KN/22/6/4343, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: yes
Client ID: oss/kn/22/1/5059, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: yes
Client ID: OSS/KN/19/3/0467, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: no
Client ID: OSS/KN/20/1/1463, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: no
Client ID: oss/kn/22/1/5174, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: yes
Client ID: OSS/KN/19/2/0896, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: no
Client ID: OSS/KN/18/0106, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: no
Client ID: oss/kn/20/1/2556, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: yes
Client ID: oss/kn/22/6/3554, Facility Name: Kano State One Stop Shop (OSS), Nasarawa, Current(ndr)?: yes
Client ID: hf/fc/22/6/0034, Facility Name: Abuja Hospital, Current(ndr)?: yes

In [5]:
with app.app_context():
    dataitems = DataEntry.query.all()

    # facility_name_choices=[item.facility_name for item in items]
    # print(facility_name_choices)
    
    # dataitem = [{'client_id': item.client_id,'laspud_po':item.laspud_po} for item in items]

    data_records = [record for record in dataitems] # if record['client_id'] == 'hf/fc/22/6/0034']
    
    for data in data_records:
        print('\n', data)

 <DataEntry oss/kn/22/2/3353>

 <DataEntry OSS/KN/22/6/4343>

 <DataEntry oss/kn/22/1/5059>

 <DataEntry OSS/KN/19/3/0467>

 <DataEntry OSS/KN/20/1/1463>

 <DataEntry oss/kn/22/1/5174>

 <DataEntry OSS/KN/19/2/0896>

 <DataEntry OSS/KN/18/0106>

 <DataEntry oss/kn/20/1/2556>

 <DataEntry oss/kn/22/6/3554>

 <DataEntry hf/fc/22/6/0034>

In [34]:
with app.app_context():
    items = DataEntry.query.all()

    facility_name_choices=[item.facility_name for item in items]
    print(facility_name_choices)
    
    dataitem = [{'client_id': item.client_id,'laspud_po':item.laspud_po} for item in items]

    existing = [record for record in dataitem if record['client_id'] == 'hf/fc/22/6/0034'][0]
    print('\n', existing)
    # a = existing[0]
    # print(a)
    if not  existing['laspud_po'] == '':
        print('existing Record!')
    else:
        print('nay')

['Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Kano State One Stop Shop (OSS), Nasarawa', 'Abuja Hospital']

 {'client_id': 'hf/fc/22/6/0034', 'laspud_po': datetime.date(2023, 4, 5)}
existing Record!

In [ ]:
with app.app_context():
    client_ids = DataEntry.query.all(facility_name)

    for client_id in client_ids:
        print(f"ID: {client_id.id}, Client Id: {client_id.client_id}")

[SQL: INSERT INTO data_entry (userid_cr, userid_pr, facility_name, client_id, client_name, sex, age, dregimen_ll, tx_age, dregimen_po, dregimen_pw, dregimen_po_correct, dregimen_pw_correct, mrefill_ll, mrefill_po, mrefill_pw, curr_ll, curr_cr, curr_pr, laspud_ll, laspud_po, laspud_pw, laspud_po_correct, laspud_pw_correct, quantityd_po, quantityd_pw, quantityd_po_correct, quantityd_pw_correct, pharm_doc, client_folder) VALUES (%(userid_cr)s, %(userid_pr)s, %(facility_name)s, %(client_id)s, %(client_name)s, %(sex)s, %(age)s, %(dregimen_ll)s, %(tx_age)s, %(dregimen_po)s, %(dregimen_pw)s, %(dregimen_po_correct)s, %(dregimen_pw_correct)s, %(mrefill_ll)s, %(mrefill_po)s, %(mrefill_pw)s, %(curr_ll)s, %(curr_cr)s, %(curr_pr)s, %(laspud_ll)s, %(laspud_po)s, %(laspud_pw)s, %(laspud_po_correct)s, %(laspud_pw_correct)s, %(quantityd_po)s, %(quantityd_pw)s, %(quantityd_po_correct)s, %(quantityd_pw_correct)s, %(pharm_doc)s, %(client_folder)s)]

[parameters: {'userid_cr': None, 'userid_pr': None, 'facility_name': 'Kano State One Stop Shop (OSS), Nasarawa', 'client_id': 'OSS/KN/23/2/8646', 'client_name': '079638cd-da39-4e1b-b424-f0939406c05d', 'sex': 'Male', 'age': 40, 'dregimen_ll': nan, 'tx_age': 0, 'dregimen_po': None, 'dregimen_pw': None, 'dregimen_po_correct': None, 'dregimen_pw_correct': None, 'mrefill_ll': nan, 'mrefill_po': None, 'mrefill_pw': None, 'curr_ll': 'yes', 'curr_cr': None, 'curr_pr': None, 'laspud_ll': Timestamp('2023-02-02 00:00:00'), 'laspud_po': None, 'laspud_pw': None, 'laspud_po_correct': None, 'laspud_pw_correct': None, 'quantityd_po': None, 'quantityd_pw': None, 'quantityd_po_correct': None, 'quantityd_pw_correct': None, 'pharm_doc': None, 'client_folder': None}]